### ISSUE TITLE
Enable processing of individual files?

### ISSUE THREAD

**Issue by bclinkinbeard** [Raynos/npm-less#3]
As discussed in https://github.com/atomify/atomify/issues/39, atomify is unable to process asset references in LESS files because we only get access to the final bundle rather than each individual file. I'm willing to do the work and submit a PR if you are amenable and it's feasible, but based on a cursory look I don't even know where to start. Do you have any suggestions as to how an event or hook could be added to enable external code to process a file before it's added to the bundle? The transformation would be synchronous.

**Comment by Raynos** [comment]
@bclinkinbeard this is the main code https://github.com/Raynos/npm-less/blob/master/index.js

You can see here https://github.com/Raynos/npm-less/blob/master/index.js#L159-L168 that we load the file that is being required for each `import` statement in LESS.

If you add some kind of synchronouse preprocessor here ( https://github.com/Raynos/npm-less/blob/master/index.js#L27 )

Something like `data = self.preprocess(data)`

Next you have to overwrite `Parser` with something like

``` js
function Parser(options) {
  var p = new LessParser(options)
  p.preprocess = options.preprocess
  return p;
}
```

Finally change https://github.com/Raynos/npm-less/blob/master/less.js#L8 so it is `less(loc, optionalObject, cb)` and pass `less(file, { preprocess: Function }, cb)`

**Comment by bclinkinbeard** [comment]
Wow, thanks for the detailed response! I will give this a go in the next few days.

**Comment by bclinkinbeard** [comment]
Closing in favor of #3
