### ISSUE TITLE
upgrade to the latest less version

### ISSUE THREAD

**Issue by spacepluk** [Raynos/npm-less#6]
Newer `less` versions have support for inline sourcemaps which I think are very nice to have.  FYI, I tried updating all `npm-less` dependencies with `npm-check-updates -u` in my local copy, and everything seems to be working fine so far.

**Comment by Raynos** [comment]
@spacepluk I added you as a collaborator :)

Feel free to make a pull request.

**Comment by spacepluk** [comment]
thanks! :)
